/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum2;

import javax.swing.JOptionPane;

/**
 *
 * @author yuyun
 */
public class no2 extends javax.swing.JFrame {
    String pilih;
    int harga;
    int jumlah;
    int total;

    /**
     * Creates new form no2
     */
    public no2() {
        initComponents();
        setTitle("Toko Makan");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bttambah = new javax.swing.JButton();
        btkurang = new javax.swing.JButton();
        txmasukkan = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        btbeli = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txpesanananda = new javax.swing.JTextField();
        txhargamakanan = new javax.swing.JTextField();
        txjumlahpesanan = new javax.swing.JTextField();
        txtotalbayar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rbnasikuning = new javax.swing.JRadioButton();
        rbnasigoreng = new javax.swing.JRadioButton();
        rbnasimawut = new javax.swing.JRadioButton();
        rbnasisoto = new javax.swing.JRadioButton();
        rbsate = new javax.swing.JRadioButton();
        rbnasipadang = new javax.swing.JRadioButton();
        rbnasirames = new javax.swing.JRadioButton();
        rbnasibakar = new javax.swing.JRadioButton();
        rbbakso = new javax.swing.JRadioButton();
        rbnasicampur = new javax.swing.JRadioButton();

        jPanel2.setBackground(new java.awt.Color(204, 102, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jPanel3.setBackground(new java.awt.Color(204, 153, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("JUMLAH BELI");

        bttambah.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        bttambah.setText("+");
        bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambahActionPerformed(evt);
            }
        });

        btkurang.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btkurang.setText("-");
        btkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkurangActionPerformed(evt);
            }
        });

        txmasukkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txmasukkanActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 51, 51));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel4.setText("INFORMASI PEMESANAN");

        btbeli.setText("BELI");
        btbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbeliActionPerformed(evt);
            }
        });

        bthapus.setText("HAPUS");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setText("PESANAN ANDA");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel6.setText("HARGA MAKANAN");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel7.setText("JUMLAH PESANAN");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel8.setText("TOTAL BAYAR");

        txpesanananda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txpesananandaActionPerformed(evt);
            }
        });

        txhargamakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txhargamakananActionPerformed(evt);
            }
        });

        txjumlahpesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txjumlahpesananActionPerformed(evt);
            }
        });

        txtotalbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtotalbayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(bttambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btkurang)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(44, 44, 44))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(27, 27, 27)
                                .addComponent(txtotalbayar))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(7, 7, 7)
                                .addComponent(txjumlahpesanan))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btbeli)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txhargamakanan)
                                            .addComponent(txpesanananda)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(bthapus))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(txmasukkan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttambah)
                    .addComponent(btkurang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txmasukkan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btbeli)
                    .addComponent(bthapus))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txpesanananda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txhargamakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txjumlahpesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtotalbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("WARUNG MAKAN MODERN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("SILAHKAN PILIH MENU");

        buttonGroup1.add(rbnasikuning);
        rbnasikuning.setText("NASI KUNING");

        buttonGroup1.add(rbnasigoreng);
        rbnasigoreng.setText("NASI GORENG");
        rbnasigoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnasigorengActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbnasimawut);
        rbnasimawut.setText("NASI MAWUT");

        buttonGroup1.add(rbnasisoto);
        rbnasisoto.setText("NASI SOTO");

        buttonGroup1.add(rbsate);
        rbsate.setText("SATE");

        rbnasipadang.setText("NASI PADANG");

        buttonGroup1.add(rbnasirames);
        rbnasirames.setText("NASI RAMES");

        buttonGroup1.add(rbnasibakar);
        rbnasibakar.setText("NASI BAKAR");

        buttonGroup1.add(rbbakso);
        rbbakso.setText("BAKSO");

        buttonGroup1.add(rbnasicampur);
        rbnasicampur.setText("NASI CAMPUR");
        rbnasicampur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnasicampurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rbnasikuning)
                                        .addComponent(rbnasigoreng))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rbnasipadang)
                                        .addComponent(rbnasirames)
                                        .addComponent(rbnasibakar)))
                                .addComponent(rbnasimawut, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbnasisoto)
                                    .addComponent(rbsate))
                                .addGap(71, 71, 71)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbbakso)
                                    .addComponent(rbnasicampur, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(39, 39, 39))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbnasikuning)
                    .addComponent(rbnasipadang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbnasigoreng)
                    .addComponent(rbnasirames))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbnasimawut)
                    .addComponent(rbnasibakar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbnasisoto)
                    .addComponent(rbbakso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbsate)
                    .addComponent(rbnasicampur))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(67, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbnasigorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnasigorengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnasigorengActionPerformed

    private void rbnasicampurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnasicampurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnasicampurActionPerformed

    private void txtotalbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtotalbayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtotalbayarActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        // TODO add your handling code here:
        jumlah =0;
        harga=0;
        total=0;
        
        txpesanananda.setText(" ");
        txhargamakanan.setText(""+harga);
        txjumlahpesanan.setText(""+jumlah);
        txtotalbayar.setText(""+total);
        txmasukkan.setText(""+jumlah);
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_bthapusActionPerformed

    private void btbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbeliActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Pesanan Anda : " +pilih + "\nHarga 1 Porsi : " + "Rp." +harga + "\nJumlah Porsi Pesanan : " +jumlah + " Porsi" + "\nTotal Bayar : " + "Rp." +total );
    }//GEN-LAST:event_btbeliActionPerformed

    private void txmasukkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txmasukkanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txmasukkanActionPerformed

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
        // TODO add your handling code here:
        try{
          pilih = "Tidak Ada";
          if (rbnasikuning.isSelected()){
            pilih ="NASI KUNING";
            harga = 7000;
            }
       if (rbnasisoto.isSelected()){
            pilih ="Nasi Soto";
            harga = 12000;
        }
       if (rbnasibakar.isSelected()){
            pilih ="Nasi Bakar";
            harga = 10000;
        }
       if (rbbakso.isSelected()){
            pilih ="Bakso";
            harga = 9500;
        }
       if (rbsate.isSelected()){
            pilih ="Sate";
            harga = 12500;
        }
       if (rbnasigoreng.isSelected()){
            pilih ="Nasi Goreng";
            harga = 13000;
        }
       if (rbnasimawut.isSelected()){
            pilih ="Nasi Mawut";
            harga = 8000;
        }
       if (rbnasicampur.isSelected()){
            pilih ="Nasi Campur";
            harga = 10500;
        }
       if (rbnasirames.isSelected()){
            pilih ="Nasi Rames";
            harga = 11500;
        }
       if (rbnasipadang.isSelected()){
            pilih ="Nasi Padang";
            harga = 15000;
        }
       
       txpesanananda.setText(pilih);
       txhargamakanan.setText("Rp." +harga);
       txmasukkan.setEditable(false);
       txpesanananda.setEditable(false);
       txhargamakanan.setEditable(false);
       txtotalbayar.setEditable(false);
       txjumlahpesanan.setEditable(false);
       
       if (pilih == "Tidak Ada"){
       txmasukkan.setText(Integer.toString(jumlah));
       }
       else{
       jumlah++;
       txmasukkan.setText(Integer.toString(jumlah));
       }
       
       txjumlahpesanan.setText(jumlah + " Porsi ");
       total = jumlah*harga;
       txtotalbayar.setText("Rp." +total);
            
        }catch(NumberFormatException ex)  {
            //menangani Numberformatexception
            JOptionPane.showConfirmDialog(this, "masukkan ");
        }
    }//GEN-LAST:event_bttambahActionPerformed

    private void txpesananandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txpesananandaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txpesananandaActionPerformed

    private void txhargamakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txhargamakananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txhargamakananActionPerformed

    private void txjumlahpesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txjumlahpesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txjumlahpesananActionPerformed

    private void btkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkurangActionPerformed
        // TODO add your handling code here:
        if (pilih == "Tidak Ada"){
       txmasukkan.setText(Integer.toString(jumlah));
       }
       else{
       jumlah--;
       txmasukkan.setText(Integer.toString(jumlah));
         if (jumlah<0){
         txmasukkan.setText("0");
         jumlah=0;
       }}
       
       txjumlahpesanan.setText(jumlah + " Porsi ");
       total = jumlah*harga;
       txtotalbayar.setText("Rp." +total);  
    }//GEN-LAST:event_btkurangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(no2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(no2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(no2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(no2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new no2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbeli;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btkurang;
    private javax.swing.JButton bttambah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbbakso;
    private javax.swing.JRadioButton rbnasibakar;
    private javax.swing.JRadioButton rbnasicampur;
    private javax.swing.JRadioButton rbnasigoreng;
    private javax.swing.JRadioButton rbnasikuning;
    private javax.swing.JRadioButton rbnasimawut;
    private javax.swing.JRadioButton rbnasipadang;
    private javax.swing.JRadioButton rbnasirames;
    private javax.swing.JRadioButton rbnasisoto;
    private javax.swing.JRadioButton rbsate;
    private javax.swing.JTextField txhargamakanan;
    private javax.swing.JTextField txjumlahpesanan;
    private javax.swing.JTextField txmasukkan;
    private javax.swing.JTextField txpesanananda;
    private javax.swing.JTextField txtotalbayar;
    // End of variables declaration//GEN-END:variables
}
